# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('multi-choice-radio', 'Multiple Choice - Single Answer (Radio Buttons)'), ('multi-choice-dropdown', 'Multiple Choice - Single Answer (Drop-down List)')], max_length=50, verbose_name='Type')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('label', models.CharField(max_length=250, verbose_name='Label (Question)')),
                ('is_required', models.BooleanField(default=True, verbose_name='Is Required?')),
            ],
            options={
                'ordering': ('form', 'number'),
                'verbose_name': 'Form Field',
                'db_table': 'field',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('assessment', 'Assessment'), ('evaluation', 'Evaluation')], max_length=50, verbose_name='Type')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Form',
                'db_table': 'form',
            },
        ),
        migrations.AddField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='forms.Form'),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together=set([('form', 'number')]),
        ),
    ]
