# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='descr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
