# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='name',
            field=models.CharField(default='default', max_length=50, verbose_name='Name (Variable)'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together=set([]),
        ),
    ]
