# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20160116_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='comment',
            new_name='descr',
        ),
        migrations.RemoveField(
            model_name='field',
            name='is_required',
        ),
        migrations.AlterField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.Form'),
        ),
        migrations.AlterField(
            model_name='field',
            name='label',
            field=models.TextField(verbose_name='Label (Question)'),
        ),
    ]
