# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20160131_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='label',
            field=models.TextField(verbose_name='Display Label (Answer)'),
        ),
        migrations.AlterField(
            model_name='field',
            name='label',
            field=models.TextField(verbose_name='Display Label (Question)'),
        ),
    ]
