# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20160118_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(verbose_name='Display Sequence')),
                ('name', models.CharField(max_length=50, verbose_name='Choice Name')),
                ('label', models.TextField(verbose_name='Label (Answer)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct Choice?')),
            ],
            options={
                'verbose_name': 'Field Choice',
                'ordering': ('field', 'sequence'),
                'db_table': 'choice',
            },
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ('form', 'sequence'), 'verbose_name': 'Form Field'},
        ),
        migrations.RemoveField(
            model_name='field',
            name='number',
        ),
        migrations.AddField(
            model_name='field',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='Display Sequence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Variable Name'),
        ),
        migrations.AlterField(
            model_name='form',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='choice',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='forms.Field'),
        ),
    ]
