# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20160122_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='descr',
            field=models.TextField(blank=True, default='default', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
