# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo')], max_length=50, verbose_name='Provider')),
                ('provider_resource_id', models.CharField(max_length=50, verbose_name='Provider ID')),
            ],
            options={
                'verbose_name': 'Video',
                'db_table': 'video',
            },
        ),
    ]
