# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 22:43
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='provider_resource',
            field=jsonfield.fields.JSONField(default={'stub': 'stub'}),
            preserve_default=False,
        ),
    ]
