# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 13:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='provider_resource',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'migration': 'default'}),
            preserve_default=False,
        ),
    ]
