# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('color', models.CharField(max_length=20, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Category',
                'db_table': 'category',
            },
        ),
    ]
