# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 14:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('forms', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('label', models.CharField(max_length=60, verbose_name='Label')),
                ('color', models.CharField(max_length=20, verbose_name='Hex Color for UX')),
            ],
            options={
                'db_table': 'category',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('descr', models.TextField(verbose_name='Description')),
                ('learning_objective', models.TextField(verbose_name='Learning Objective')),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment', to='forms.Form')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='authors.Author')),
            ],
            options={
                'db_table': 'course',
                'verbose_name': 'Course',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Course')),
            ],
            options={
                'db_table': 'course_category',
                'verbose_name': 'Course Category',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('label', models.CharField(max_length=60, verbose_name='Label')),
                ('descr', models.TextField(verbose_name='Description')),
            ],
            options={
                'db_table': 'credit',
                'verbose_name': 'CME Credit',
            },
        ),
        migrations.CreateModel(
            name='PubCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_on', models.DateTimeField(auto_now_add=True, verbose_name='Pub Version Date')),
                ('version_number', models.IntegerField(verbose_name='Pub Version')),
                ('is_current_version', models.BooleanField(verbose_name='Current Pub Version')),
                ('release_on', models.DateTimeField(verbose_name='Pub Release Date')),
                ('expire_on', models.DateTimeField(verbose_name='Pub Expire Date')),
                ('content_jsonb', django.contrib.postgres.fields.jsonb.JSONField()),
                ('content_json', jsonfield.fields.JSONField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pub_courses', to='content.Course')),
            ],
            options={
                'db_table': 'pub_course',
                'verbose_name': 'Course',
                'ordering': ('course', '-version_number'),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='content.Credit'),
        ),
        migrations.AddField(
            model_name='course',
            name='evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation', to='forms.Form'),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='videos.Video'),
        ),
        migrations.AlterUniqueTogether(
            name='coursecategory',
            unique_together=set([('course', 'category')]),
        ),
    ]
