# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('descr', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'CME Credit',
                'db_table': 'credit',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Hex Color for UX'),
        ),
    ]
