# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Course Video',
                'db_table': 'course_video',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(through='content.CourseAuthor', to='authors.Author'),
        ),
        migrations.AlterField(
            model_name='courseauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_courses', to='authors.Author'),
        ),
        migrations.AlterField(
            model_name='courseauthor',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_authors', to='content.Course', unique=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='content.Course', unique=True),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video'),
        ),
    ]
