# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 15:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(verbose_name='Pub Version')),
                ('version_on', models.DateTimeField(auto_now_add=True, verbose_name='Pub Version Date')),
                ('is_current_version', models.BooleanField(default=True, verbose_name='Current Pub Version')),
                ('release_on', models.DateTimeField(verbose_name='Pub Release Date')),
                ('expire_on', models.DateTimeField(verbose_name='Pub Expire Date')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'pub_course',
                'verbose_name': 'Course',
            },
        ),
    ]
