# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_pubcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubcourse',
            name='course',
            field=models.ForeignKey(default='2add96e2-6b88-420e-a1ee-128371f825f8', on_delete=django.db.models.deletion.PROTECT, to='content.Course'),
            preserve_default=False,
        ),
    ]
