# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20160131_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='courseauthor',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursevideo',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursevideo',
            name='video',
        ),
        migrations.RemoveField(
            model_name='course',
            name='authors',
        ),
        migrations.DeleteModel(
            name='CourseAuthor',
        ),
        migrations.DeleteModel(
            name='CourseVideo',
        ),
    ]
