# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_pubcourse_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pubcourse',
            options={'ordering': ('course', '-version_number'), 'verbose_name': 'Course'},
        ),
        migrations.RenameField(
            model_name='pubcourse',
            old_name='content',
            new_name='content_jsonb',
        ),
        migrations.AddField(
            model_name='pubcourse',
            name='content_json',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pubcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pub_courses', to='content.Course'),
        ),
        migrations.AlterField(
            model_name='pubcourse',
            name='is_current_version',
            field=models.BooleanField(verbose_name='Current Pub Version'),
        ),
    ]
