# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('forms', '0001_initial'),
        ('content', '0005_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment', to='forms.Form'),
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='content.Credit'),
        ),
        migrations.AddField(
            model_name='course',
            name='evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation', to='forms.Form'),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='videos.Video'),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='authors.Author'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='content.Category'),
        ),
    ]
