# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 13:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('headline', models.TextField(verbose_name='Headline')),
                ('thumbnails_headline_url', models.CharField(max_length=240, validators=[django.core.validators.URLValidator()], verbose_name='Headline Thumbnail (portrait) URL')),
                ('disclosure_statement', models.TextField(verbose_name='Disclosure Summary')),
                ('disclosure_expire_on', models.DateTimeField(verbose_name='Disclosure Expire On')),
            ],
            options={
                'db_table': 'author',
                'verbose_name': 'Author',
            },
        ),
    ]
