# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 14:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Title')),
                ('headline', models.TextField(verbose_name='Headline')),
                ('headline_thumbnail_url', models.CharField(max_length=240, validators=[django.core.validators.URLValidator()], verbose_name='Headline Portrait URL')),
                ('disclosure_statement', models.TextField(verbose_name='Disclosure Summary')),
                ('disclosure_expire_on', models.DateTimeField(verbose_name='Disclosure Expire On')),
            ],
            options={
                'db_table': 'author',
                'verbose_name': 'Author',
            },
        ),
    ]
