# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 21:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='headline_thumbnail_url',
        ),
        migrations.AddField(
            model_name='author',
            name='thumbnails_headline_url',
            field=models.CharField(default='https://noimage.org/noimage.png', max_length=240, validators=[django.core.validators.URLValidator()], verbose_name='Headline Thumbnail (portrait) URL'),
            preserve_default=False,
        ),
    ]
