# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 18:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='disclosure_summary',
            new_name='disclosure_statement',
        ),
        migrations.AlterField(
            model_name='author',
            name='disclosure_expires_on',
            field=models.DateTimeField(null=True, verbose_name='Disclosure Expires On'),
        ),
        migrations.AlterField(
            model_name='author',
            name='headline_thumbnail_url',
            field=models.CharField(max_length=240, validators=[django.core.validators.URLValidator()], verbose_name='Headline Portrait URL'),
        ),
    ]
