# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_auto_20160125_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='disclosure_expires_on',
        ),
        migrations.AddField(
            model_name='author',
            name='disclosure_expire_on',
            field=models.DateTimeField(null=True, verbose_name='Disclosure Expire On'),
        ),
        migrations.AlterField(
            model_name='author',
            name='disclosure_statement',
            field=models.TextField(blank=True, default='default', verbose_name='Disclosure Summary'),
            preserve_default=False,
        ),
    ]
